### ISSUE TITLE
Too Whitespace sensitive

### ISSUE THREAD

**Issue by ybisk** [christos-c/tree-viewer#1]
Works:  `(<T S[dcl] 0 2> (<L (S/S)/NP IN IN For (S_280/S_280)/NP_281>))`
Doesn't: `(<T S[dcl] 0 2> (<L (S/S)/NP IN IN  For (S_280/S_280)/NP_281>))`

**Comment by christos-c** [comment]
Fixed. Thanks for spotting this!
